#!/bin/bash
#
# reference link: http://makezine.com/projects/send-ticket-isp-when-your-internet-drops/
# NOTE should NOT neet to edit this for other than debian8 user ...
sudo apt-get install python-pip -y
sudo apt-get install curl -y
sudo pip install speedtest-cli
# add crontab 
crontab -l >tmp
echo "0 * * * * /home/$USER/spt/speedtest-cron.sh" >>tmp
crontab tmp 
rm tmp 
crontab -l
